name: 'Fetch Terraform Output Value'
description: 'Fetches a Terraform output value from the specified state file.'
inputs:
  backend-configuration:
    description: 'The Terraform backend configuration as a JSON string.'
    required: true
  include-sensitive:
    description: 'Include output values marked as "sensitive". Expected values are "yes" or "no".'
    default: 'no'
    required: false
outputs:
  outputs:
    description: 'A JSON string that represents the output values.'
runs:
  using: 'node20'
  main: 'dist/index.js'
